using System.IO;
using UnityEditor;
using UnityEngine;

namespace Prasanna.MobileSetup.Editor
{
    /// <summary>
    /// Step 08 — UI Toolkit Setup
    ///
    /// Creates starter UI Toolkit files:
    ///   · Assets/UI/UXML/MainUI.uxml — root UI document template
    ///   · Assets/UI/USS/MainUI.uss   — base stylesheet
    ///
    /// Existing files are not overwritten (safe to re-run).
    /// </summary>
    public class Step08_UIToolkitSetup : SetupStepBase
    {
        public Step08_UIToolkitSetup()
        {
            Name        = "UI Toolkit Setup";
            Description = "Creates MainUI.uxml and MainUI.uss starter templates in Assets/UI/.";
        }

        protected override void Run()
        {
            string projectRoot = Application.dataPath.Replace("/Assets", "");
            int    created     = 0;

            // ── UXML ──────────────────────────────────────────────────────────────
            string uxmlFullPath = Path.Combine(projectRoot, SetupConfig.MainUXMLPath);
            if (!File.Exists(uxmlFullPath))
            {
                EnsureDirectory(Path.GetDirectoryName(uxmlFullPath));
                File.WriteAllText(uxmlFullPath, BuildUXML());
                created++;
            }

            // ── USS ───────────────────────────────────────────────────────────────
            string ussFullPath = Path.Combine(projectRoot, SetupConfig.MainUSSPath);
            if (!File.Exists(ussFullPath))
            {
                EnsureDirectory(Path.GetDirectoryName(ussFullPath));
                File.WriteAllText(ussFullPath, BuildUSS());
                created++;
            }

            AssetDatabase.Refresh();

            if (created == 0)
                Succeed("UXML and USS files already exist — skipped.");
            else
                Succeed($"Created {created} UI Toolkit file(s). " +
                        "Attach a UIDocument component to a GameObject and assign MainUI.uxml.");
        }

        // ── File Templates ────────────────────────────────────────────────────────

        private static string BuildUXML() =>
@"<ui:UXML
    xmlns:ui=""UnityEngine.UIElements""
    xmlns:uie=""UnityEditor.UIElements""
    xsi=""http://www.w3.org/2001/XMLSchema-instance""
    engine=""UnityEngine.UIElements""
    editor=""UnityEditor.UIElements""
    noNamespaceSchemaLocation=""../../../UIElementsSchema/UIElements.xsd""
    editor-extension-mode=""False"">

    <!--
        MainUI.uxml — Root UI Document
        Generated by com.prasanna.mobilesetup
    -->

    <Style src=""project://database/Assets/UI/USS/MainUI.uss"" />

    <ui:VisualElement name=""root"" class=""root-container"">

        <ui:VisualElement name=""header"" class=""header"">
            <ui:Label name=""title-label"" text=""Game Title"" class=""title"" />
        </ui:VisualElement>

        <ui:VisualElement name=""content"" class=""content"">
            <!-- Add your UI elements here -->
        </ui:VisualElement>

        <ui:VisualElement name=""footer"" class=""footer"">
            <ui:Button name=""action-button"" text=""Play"" class=""btn btn-primary"" />
        </ui:VisualElement>

    </ui:VisualElement>

</ui:UXML>
";

        private static string BuildUSS() =>
@"/*
 * MainUI.uss — Base Stylesheet
 * Generated by com.prasanna.mobilesetup
 */

/* ── Variables ─────────────────────────────────────────────────────────────── */
:root {
    --color-bg:        rgb(20, 20, 30);
    --color-primary:   rgb(90, 180, 255);
    --color-text:      rgb(230, 230, 230);
    --color-text-muted: rgb(140, 140, 150);
    --radius:          12px;
    --spacing-sm:      8px;
    --spacing-md:      16px;
    --spacing-lg:      24px;
}

/* ── Root Container ─────────────────────────────────────────────────────────── */
.root-container {
    flex-grow: 1;
    flex-direction: column;
    background-color: var(--color-bg);
    padding: var(--spacing-md);
}

/* ── Header ─────────────────────────────────────────────────────────────────── */
.header {
    align-items: center;
    padding-top: var(--spacing-lg);
    padding-bottom: var(--spacing-md);
}

.title {
    font-size: 32px;
    color: var(--color-primary);
    -unity-font-style: bold;
    -unity-text-align: upper-center;
}

/* ── Content ─────────────────────────────────────────────────────────────────── */
.content {
    flex-grow: 1;
    align-items: center;
    justify-content: center;
}

/* ── Footer ─────────────────────────────────────────────────────────────────── */
.footer {
    align-items: center;
    padding-bottom: var(--spacing-lg);
}

/* ── Buttons ─────────────────────────────────────────────────────────────────── */
.btn {
    border-radius: var(--radius);
    padding: var(--spacing-sm) var(--spacing-lg);
    font-size: 18px;
    -unity-font-style: bold;
    border-width: 0;
    cursor: link;
}

.btn-primary {
    background-color: var(--color-primary);
    color: rgb(10, 10, 20);
}

.btn-primary:hover {
    background-color: rgb(120, 200, 255);
}
";

        // ── Helpers ───────────────────────────────────────────────────────────────

        private static void EnsureDirectory(string dir)
        {
            if (!string.IsNullOrEmpty(dir) && !Directory.Exists(dir))
                Directory.CreateDirectory(dir);
        }
    }
}
